;;; memex-entry.el --- A call and what it returned -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Sören Nikolaus

;; Author: Sören Nikolaus <soeren@code17.io>
;; Version: 0.1.0
;; Package-Requires: ((emacs "29.1"))
;; Keywords: convenience, tools, matching
;; URL: https://github.com/srnnkls/memex.el

;;; Commentary:

;; memex sends a tool call and its result as two records, joined by the
;; result's `parent_tool_use_id'.  Read apart they are two entries that
;; each show the same text twice - a call whose `text' is a copy of its
;; arguments, then a result whose `text' is a copy of its output.
;; `memex-entry-pair' puts them back together, and the rest of this file
;; answers what a reader wants off the pair: what it was for, whether it
;; worked, what it was given and what it returned.
;;
;; Arguments arrive as a Rust `Debug' rendering of a map rather than as
;; JSON.  `memex-entry-fields' reads whatever keys a tool used instead of
;; looking for known ones, since every tool has its own.
;;
;; Two things a reader wants are not in what memex records.  There is no
;; exit status, so a call that failed under a zero exit is visible only
;; in what it printed - hence `warn' rather than a failure.  And output
;; is one field, so stdout and stderr cannot be told apart.

;;; Code:

(require 'cl-lib)
(require 'rx)
(require 'seq)
(require 'subr-x)

(defgroup memex-entry nil
  "The call-and-result pairs a transcript is made of."
  :group 'memex)

(defcustom memex-entry-payload-threshold 200
  "Length past which an argument is shown as a section of its own.
A command belongs on the metadata block; a file's contents do not."
  :type 'natnum
  :group 'memex-entry)

(defcustom memex-entry-failure
  (rx (or (seq (in "1-9") (* digit) " unexpected")
          "FAILED" "Traceback" "panicked at" "command not found"
          "No such file" "Permission denied" "AssertionError" "SyntaxError"
          (seq bol (* (in " \t")) (or "error:" "Error:" "ERROR:" "fatal:"))))
  "What in a tool's output marks it as having gone wrong.
memex records no exit status, so this is the only evidence there is:
a suite reporting `1 unexpected' exits 0 all the same."
  :type 'regexp
  :group 'memex-entry)

(defcustom memex-entry-skipped
  (rx bos (* (in " \t\n")) (? "Error: ")
      (or "[Request interrupted by user"
          "The user doesn't want to proceed with this tool use"))
  "What in a tool's output marks the call as never having run.
A denied call and a failed one read the same in a transcript that only
has output to go on, and they are opposite things: nothing happened, and
the reader is the reason.  The harness writes both of these verbatim.

It is anchored for the reason `memex-entry-quoting' exists: a call that
greps a transcript for the denial prints it, and prints it in the middle
of what it found rather than as the whole of what it returned."
  :type 'regexp
  :group 'memex-entry)

(defcustom memex-entry-injected
  (rx bos (* (in " \t\n"))
      (or (seq "<" (+ (in "a-z" "_-")) (in " >\n"))
          "Caveat: The messages below were generated by the user"
          "Base directory for this skill:"
          "This session is being continued from"))
  "What opens a `user' record the harness wrote rather than a person.
A transcript carries far more of these than of anything anyone typed -
skill bodies, slash commands and their output, file mentions, task
notifications - and they all arrive under the role of the person whose
turn they were injected into.  Every one of them opens with a tag, and
nobody opens a question with one, so the tag is what they are told by
rather than a list of the tags there have been so far.

Mistaking a person for the harness costs a reader the question the
session was about, and the reverse costs them a line to skip past, so
this is worth keeping narrow."
  :type 'regexp
  :group 'memex-entry)

(defcustom memex-entry-quoting
  '("Read" "Glob" "Grep" "NotebookRead" "ToolSearch" "WebFetch" "WebSearch")
  "Tools whose output is what they were asked to fetch, not a report.
`memex-entry-failure' is read against what a call printed, and a file
that happens to say `error:' says nothing about the call that read it."
  :type '(repeat string)
  :group 'memex-entry)

(defcustom memex-entry-principal
  '(("Bash" . "command") ("BashOutput" . "command") ("KillShell" . "command")
    ("Write" . "content") ("Edit" . "new_string") ("MultiEdit" . "edits")
    ("NotebookEdit" . "new_source"))
  "The argument carrying what each tool was actually asked to run.
It gets a section of its own however short it is.  A one-line command
and a hundred-line patch are the same thing to a reader looking for what
happened, and putting one on the metadata block and the other behind a
fold makes one transcript read two ways."
  :type '(alist :key-type string :value-type string)
  :group 'memex-entry)

(defconst memex-entry--heading-keys '("description" "prompt" "query" "pattern")
  "Argument keys already written for a reader, best first.")

(defconst memex-entry--path-keys '("file_path" "path" "notebook_path")
  "Argument keys naming the file a tool touched, best first.")


(defun memex-entry--unescape (text)
  "Return TEXT with the escapes a Rust `Debug' string carries resolved."
  (with-temp-buffer
    (insert text)
    (goto-char (point-min))
    (while (search-forward "\\" nil t)
      (let ((escaped (char-after)))
        (delete-char -1)
        (when escaped
          (delete-char 1)
          (insert (pcase escaped
                    (?n "\n") (?t "\t") (?r "\r") (?0 "\0")
                    (_ (string escaped)))))))
    (buffer-string)))

(defun memex-entry--read-string (text position)
  "Return (VALUE . END) for the quoted run of TEXT at POSITION.
A tool's arguments carry their own quotes and braces, so the run ends at
the first quote that is not escaped rather than at the first quote."
  (let ((i (1+ position))
        (n (length text))
        (start (1+ position)))
    (while (and (< i n)
                (not (eq (aref text i) ?\")))
      (setq i (if (eq (aref text i) ?\\) (+ i 2) (1+ i))))
    (cons (memex-entry--unescape (substring text start (min i n)))
          (min (1+ i) n))))

(defun memex-entry--read-value (text position)
  "Return (VALUE . END) for the argument value of TEXT at POSITION.
A wrapper naming a scalar - `String', `Number', `Bool' - is unwrapped to
what it holds.  Anything nested is returned as it was written, since
reading it is the payload section's job."
  (let ((n (length text))
        (i position))
    (while (and (< i n) (memq (aref text i) '(?\s ?\t ?\n))) (setq i (1+ i)))
    (cond
     ((>= i n) (cons "" n))
     ((eq (aref text i) ?\") (memex-entry--read-string text i))
     (t
      (let ((start i) (depth 0) (done nil))
        (while (and (< i n) (not done))
          (let ((c (aref text i)))
            (cond
             ((eq c ?\") (setq i (cdr (memex-entry--read-string text i))))
             ((memq c '(?\( ?\[ ?{)) (setq depth (1+ depth) i (1+ i)))
             ((memq c '(?\) ?\] ?}))
              (if (zerop depth) (setq done t) (setq depth (1- depth) i (1+ i))))
             ((and (eq c ?,) (zerop depth)) (setq done t))
             (t (setq i (1+ i))))))
        (let ((raw (string-trim (substring text start i))))
          (cons (if (string-match
                     (rx bos (or "String" "Number" "Bool" "Static" "Integer"
                                 "Float")
                         "(" (group (*? anychar)) ")" eos)
                     raw)
                    (let ((inner (match-string 1 raw)))
                      (if (string-prefix-p "\"" inner)
                          (car (memex-entry--read-string inner 0))
                        (car (memex-entry--read-value inner 0))))
                  raw)
                i)))))))

(defun memex-entry-fields (input)
  "Return the arguments in INPUT as an alist, in the order written.
INPUT is a Rust `Debug' rendering of a map, which is how memex records a
tool's arguments.  Nil for nothing to read."
  (when (and input (not (string-empty-p input)))
    (let ((i 0) (n (length input)) (fields nil) (depth 0))
      (while (< i n)
        (let ((c (aref input i)))
          (cond
           ((memq c '(?\( ?\[ ?{)) (setq depth (1+ depth) i (1+ i)))
           ((memq c '(?\) ?\] ?})) (setq depth (1- depth) i (1+ i)))
           ((and (eq c ?\") (equal depth 1))
            (pcase-let* ((`(,key . ,after) (memex-entry--read-string input i))
                         (rest after))
              (while (and (< rest n) (memq (aref input rest) '(?\s ?\t ?\n)))
                (setq rest (1+ rest)))
              (if (and (< rest n) (eq (aref input rest) ?:))
                  (pcase-let ((`(,value . ,end)
                               (memex-entry--read-value input (1+ rest))))
                    (push (cons key value) fields)
                    (setq i end))
                (setq i after))))
           ((eq c ?\") (setq i (cdr (memex-entry--read-string input i))))
           (t (setq i (1+ i))))))
      (nreverse fields))))

(defvar memex-entry--fields-cache nil
  "Dynamically bound cache of parsed fields keyed by entry identity.")

(defconst memex-entry--cache-miss (make-symbol "memex-entry-cache-miss")
  "Value distinguishing an absent cached entry from cached nil fields.")

(defun memex-entry--fields (entry)
  "Return ENTRY's parsed tool fields, reusing a dynamically bound cache."
  (let ((input (alist-get 'tool_input (car entry))))
    (if (null memex-entry--fields-cache)
        (memex-entry-fields input)
      (let ((fields (gethash entry memex-entry--fields-cache
                             memex-entry--cache-miss)))
        (if (not (eq fields memex-entry--cache-miss))
            fields
          (setq fields (memex-entry-fields input))
          (puthash entry fields memex-entry--fields-cache)
          fields)))))


(defun memex-entry-call (entry)
  "Return the record ENTRY was opened by."
  (car entry))

(defun memex-entry-result (entry)
  "Return what ENTRY's call returned, or nil for a call with no result."
  (cdr entry))

(defun memex-entry-pair (records)
  "Return RECORDS as entries, each a call consed onto what it returned.
A result is joined to the call whose `event_id' its `parent_tool_use_id'
names.  A result whose call is not in RECORDS stands as an entry of its
own: a page can begin after the call it answers."
  (let ((calls (make-hash-table :test 'equal))
        (entries nil))
    (dolist (record records)
      (let ((parent (alist-get 'parent_tool_use_id record)))
        (if-let* ((cell (and parent (gethash parent calls))))
            (setcdr cell record)
          (let ((cell (cons record nil)))
            (when-let* ((id (alist-get 'event_id record)))
              (puthash id cell calls))
            (push cell entries)))))
    (nreverse entries)))


(defun memex-entry-duration (entry)
  "Return how long ENTRY took in milliseconds, or nil while it is open."
  (let ((call (memex-entry-call entry))
        (result (memex-entry-result entry)))
    (when result
      (let ((from (alist-get 'ts call))
            (to (alist-get 'ts result)))
        (and (numberp from) (numberp to) (- to from))))))

(defun memex-entry-tool (entry)
  "Return the name of the tool ENTRY called, or nil for a message."
  (alist-get 'tool_name (memex-entry-call entry)))

(defun memex-entry-kind (entry)
  "Return what ENTRY is: `human', `assistant', `tool' or `system'.
The four are what a reader filters a transcript by, and only the first
two are anyone talking.  Roles memex records beyond those - `developer'
is codex's - are the harness setting a session up, so they read as
`system' along with everything injected into a person's turn."
  (let* ((call (memex-entry-call entry))
         (role (alist-get 'role call)))
    (cond
     ((memex-entry-tool entry) 'tool)
     ((equal role "assistant") 'assistant)
     ((equal role "user")
      (if (string-match-p memex-entry-injected (or (alist-get 'text call) ""))
          'system
        'human))
     (t 'system))))

(defun memex-entry-description (entry)
  "Return the line ENTRY is worth heading with.
What the agent wrote for a reader comes first, then the file it touched,
then the opening line of a message.  The role never does: it is what the
section's own type and nesting already say."
  (let* ((call (memex-entry-call entry))
         (fields (memex-entry--fields entry)))
    (or (seq-some (lambda (key) (alist-get key fields nil nil #'equal))
                  memex-entry--heading-keys)
        (when-let* ((path (seq-some (lambda (key)
                                      (alist-get key fields nil nil #'equal))
                                    memex-entry--path-keys)))
          (file-name-nondirectory (directory-file-name path)))
        (when-let* ((text (alist-get 'text call))
                    ((not (memex-entry-tool entry))))
          (car (split-string text "\n" t)))
        (memex-entry-tool entry)
        "")))

(defun memex-entry-status (entry)
  "Return ENTRY's outcome as (STATE . REASON).
STATE is `ok', `warn', `skipped' or `pending'.  There is no failed
state: memex records no exit status, so a call that failed is only ever
as visible as what it printed, and REASON is the line that said so.
`skipped' is read first, because the harness prefixes a denial with
`Error:' and that is not what went wrong; it carries no reason, the
boilerplate holding none a heading is better for.  What each state is
drawn as belongs to whoever is drawing it."
  (let ((result (memex-entry-result entry)))
    (cond
     ((null result)
      (cons (if (memex-entry-tool entry) 'pending 'ok) nil))
     ((let ((case-fold-search nil))
        (when-let* ((output (memex-entry-output entry))
                    ((string-match-p memex-entry-skipped output)))
          (cons 'skipped nil))))
     ((let ((case-fold-search nil))
        (when-let* (((not (member (memex-entry-tool entry) memex-entry-quoting)))
                    (output (memex-entry-output entry))
                    ((string-match memex-entry-failure output)))
          (cons 'warn (memex-entry--reason output (match-beginning 0))))))
     (t (cons 'ok nil)))))

(defun memex-entry--reason (output position)
  "Return the line of OUTPUT that POSITION falls on, trimmed."
  (let ((start (or (and (> position 0)
                        (cl-position ?\n output :end position :from-end t :test #'eql))
                   -1))
        (end (or (cl-position ?\n output :start position :test #'eql) (length output))))
    (string-trim (substring output (1+ start) end))))

(defun memex-entry-output (entry)
  "Return what ENTRY returned, or nil for a call that returned nothing.
A result whose call is not in the page stands as its own entry, and what
it returned is on the record itself rather than on a result beside it."
  (let ((result (or (memex-entry-result entry)
                    (let ((call (memex-entry-call entry)))
                      (and (equal (alist-get 'role call) "tool_result") call)))))
    (when result
      (or (alist-get 'tool_output result) (alist-get 'text result)))))

(defun memex-entry-payload (entry)
  "Return ENTRY's principal argument as (KEY MODE . TEXT), or nil for none.
What a tool was asked to run belongs in a section of its own, headed by
the name the tool gave it; the mode comes from the path it touched.
`memex-entry-principal' names that argument per tool, and any argument
too long to read on one line falls back to the same treatment."
  (let* ((fields (memex-entry--fields entry))
         (path (seq-some (lambda (key) (alist-get key fields nil nil #'equal))
                         memex-entry--path-keys))
         (principal (assoc-default (memex-entry-tool entry)
                                   memex-entry-principal))
         (long (or (and principal (assoc principal fields))
                   (seq-find (lambda (field)
                               (and (not (member (car field)
                                                 memex-entry--path-keys))
                                    (> (length (cdr field))
                                       memex-entry-payload-threshold)))
                             fields))))
    (when long
      (cons (car long)
            (cons (and path (assoc-default path auto-mode-alist #'string-match))
                  (cdr long))))))

(defun memex-entry-metadata (entry)
  "Return the aligned block ENTRY is worth showing above its body.
Every argument short enough to read on one line, the arguments already
spent on the heading left out, then what the call returned in numbers."
  (let* ((fields (memex-entry--fields entry))
         (payload (cddr (memex-entry-payload entry)))
         (output (memex-entry-output entry))
         (meta nil))
    (dolist (field fields)
      (unless (or (member (car field) memex-entry--heading-keys)
                  (equal (cdr field) payload)
                  (> (length (cdr field)) memex-entry-payload-threshold))
        (push field meta)))
    (when output
      (push (cons "lines" (number-to-string
                           (length (split-string output "\n" t))))
            meta)
      (push (cons "bytes" (number-to-string (string-bytes output))) meta))
    (when-let* ((took (memex-entry-duration entry)))
      (push (cons "took" (if (< took 1000)
                             (format "%dms" took)
                           (format "%.1fs" (/ took 1000.0))))
            meta))
    (nreverse meta)))

(provide 'memex-entry)
;;; memex-entry.el ends here
